<?php
/**
 * @license Copyright 2011-2014 HycPay Inc., MIT License
 * @see https://github.com/hycpay/magento-plugin/blob/master/LICENSE
 */

/**
 * @see Hycpay_Core_Block_Adminhtml_System_Config_Form_Field_Header
 */
 
echo '<div style="background-color:#002855;padding:5px;color:#ffffff">' .
        '<img src="https://raw.githubusercontent.com/hycpay/hycpay-brand/master/hycpay-logo-primary.png" alt="HycPay" witdth="113" height="44" />' .
        '<a style="color:#ffffff;font-family:\'Ubuntu\',sans-serif;text-decoration:none;margin:15px" href="https://support.hycpay.com/?ref=magento" target="_blank">Support</a>' .
        '<a style="color:#ffffff;font-family:\'Ubuntu\',sans-serif;text-decoration:none;margin:15px" href="https://hycpay.com/start?ref=magento" target="_blank">Sign Up</a>' .
        '<a style="color:#ffffff;font-family:\'Ubuntu\',sans-serif;text-decoration:none;margin:15px" href="https://hycpay.com/merchant-login?ref=magento" target="_blank">Login</a>' .
     '</div>';

?>
