<?php
/**
 * @license Copyright 2011-2014 HycPay Inc., MIT License
 * @see https://github.com/hycpay/magento-plugin/blob/master/LICENSE
 */

/**
 * @see Hycpay_Core_Block_Form_Hycpay
 */
 
$_code = $this->getMethodCode();
if (Mage::getStoreConfig('payment/hycpay/fullscreen')) {
	echo '<ul class="form-list" id="payment_form_' . $_code . '" style="display:none;">' .
	         '<li>You will be transfered to <a href="https://hycpay.com" target="_blank">HycPay</a> to complete your purchase when using this payment method.</li>' .
	     '</ul>';
}
?>
